language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t reysmerwvr/docker-react -f Dockerfile.dev .
#script:
#  - docker run USERNAME/docker-react npm run test -- --coverage
script:
  - docker run -e CI=true reysmerwvr/docker-react npm run test